# -*- coding: utf-8 -*-
# QGIS: 4.0.0
# Qt: 6 / PyQt6 6.11.0
# Modificado em: 2026-08-09

# Form implementation generated from reading ui file 'qad.ui'
#
# Created by: qgis.PyQt UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


